### ISSUE TITLE
Error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by sagitter** [Cantera/cantera#369]
Hi all.

This error comes out by compiling `cantera`\- ad7a02d0e9653a04b98d882b0a6d6de3198720da on Fedora 26 (development branch) with `fmt-3.0.0`:

```
g++ -o build/src/thermo/FixedChemPotSSTP.os -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -Wl,-z,now --std=c++14 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -Wl,-z,now -pthread -DNDEBUG -Wall -fPIC -DNDEBUG -Iinclude -Iinclude/cantera/ext -I/usr/include/eigen3 -I/usr/include src/thermo/FixedChemPotSSTP.cpp
In file included from /usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/limits.h:168:0,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/limits.h:34,
                 from /usr/include/c++/6.2.1/climits:42,
                 from /usr/include/eigen3/Eigen/Core:158,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from include/cantera/numerics/eigen_dense.h:5,
                 from src/numerics/polyfit.cpp:7:
/usr/include/fmt/format.h: In member function 'void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int)':
/usr/include/fmt/format.h:1825:20: error: expected unqualified-id before numeric constant
     const unsigned CHAR_WIDTH = 1;
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/1738/16101738/build.log

Can you take a look please?

**Comment by speth** [comment]
- As you well know, `format.h` is not part of Cantera, so it's not clear how this is a bug in Cantera
- I think your logs are jumbled because of the parallel build (if the error is in compiling `FixedChemPotSSTP.cpp`, the error shouldn't reference `polyfit.cpp`). Can you please run a single-threaded build to pin down the actual error?
- You haven't provided any useful information about the system that this is compiling on (at a minimum, what version of GCC?) or whether it's compiling successfully elsewhere to be able to determine what's special about this configuration

**Comment by sagitter** [comment]
Hi Speth.

Rebuild without parallel build on Fedora 26 32bit.
Full build log: https://kojipkgs.fedoraproject.org//work/tasks/2569/16102569/build.log
List of used dependencies: https://kojipkgs.fedoraproject.org//work/tasks/2569/16102569/root.log

**Comment by speth** [comment]
The problem appears to be the fact that `CHAR_WIDTH` is a macro defined in a libc header. As far as I can tell, this only exists in the development version of GCC (introduced in https://github.com/gcc-mirror/gcc/commit/c5eddaf97b1387dd05b6534878662f1769e91e1c). This commit occurred _after_ the latest GCC release (6.2.0). I'm not sure what gcc version "6.2.1-2.fc26" is supposed to be, since 6.2.1 hasn't even been released, so I guess it's a random snapshot of the development version that includes this commit.

I'll aso note that `CHAR_WIDTH` does not fit the pattern of names reserved by libc:
http://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html
so if anything, this might be regarded as a bug in libc.

In any case, this is in no way, shape or form a bug in Cantera.
