### ISSUE TITLE
SUNDIALS 4.1.0 does not work with Cantera 2.4.0

### ISSUE THREAD

**Issue by ghost** [Cantera/cantera#620]
### Cantera version
2.4.0
### Operating System
Linux, RHEL6
### Python/MATLAB version
3.6.3
### Expected Behavior
Build successfully
### Actual Behavior
Failed because `CV_NEWTON` cannot be found in sundials 4.1.0

last part of `config.log` is 
```
scons: Configure: Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... 
.sconf_temp/conftest_10.cpp <-
  |
  |
  |#include "cvodes/cvodes.h"
  |int
  |main() {
  |  CVodeCreate(CV_BDF, CV_NEWTON);
  |return 0;
  |}
  |
g++ -o .sconf_temp/conftest_10.o -c -std=c++0x -pthread -O3 -Wno-inline -g -DNDEBUG -I/PARA/pp569/share/eigen/3.3.7/include/eigen3 -I/PARA/pp569/share/fmt/5.3.0/include -I/PARA/pp569/share/googletest/1.8.1/include -I/PARA/pp569/share/boost/1.69.0/include -I/PARA/pp569/share/sundials/4.1.0/include .sconf_temp/conftest_10.cpp
.sconf_temp/conftest_10.cpp: In function 'int main()':
.sconf_temp/conftest_10.cpp:6:23: error: 'CV_NEWTON' was not declared in this scope
   CVodeCreate(CV_BDF, CV_NEWTON);
                       ^
scons: Configure: no
```
### Steps to reproduce

just install sundials 4.1.0 and compile cantera 2.4.0

I found this:
`With the introduction of SUNNonlinSol modules, the input parameter iter to CVodeCreate has been **removed** along with the function CVodeSetIterType and the **constants CV_NEWTON** and CV_FUNCTIONAL.`
in https://computation.llnl.gov/projects/sundials/release-history

And I searched the headers of sundials but no `CV_NEWTON` keyword was found.

According to 

https://github.com/Cantera/cantera/blob/master/.gitmodules

and 

https://github.com/Cantera/sundials-mirror

sundials 3.1.0 was used by default.

So I think it is caused by upgrade of sundials.

**Comment by bryanwweber** [comment]
For reference this was also reported on the User Group: https://groups.google.com/forum/#!searchin/cantera-users/sundials$204.1%7Csort:date/cantera-users/m3MtGtDmtf0/tF9O4RpaAQAJ
