### PR TITLE
Fix missing include in ReactionData.h

### LINKED ISSUE #999: Compiling failure on Windows
**Problem description**

Compiling with MSVC 14.2 on Windows 10 from MS Visual Studio 2019 gives the following error message:

```
cl /Fobuild\src\kinetics\ReactionData.obj /c src\kinetics\ReactionData.cpp /EHsc /MD /nologo /D_SCL_SECURE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS /O2 /Zi /Fdbuild\src\kinetics\ReactionData.obj.pdb /W3 /DNDEBUG  /Iinclude /Iinclude\cantera\ext /Ibuild\src /IC:\Users\bww09001\Miniconda3\envs\cantera-dev\Library\include ReactionData.cpp C:\Users\bww09001\Documents\GitHub\cantera\include\cantera/kinetics/ReactionData.h(43): error C2039: 'log': is not a member of 'std' predefined C++ types (compiler internal)(340): note: see declaration of 'std' C:\Users\bww09001\Documents\GitHub\cantera\include\cantera/kinetics/ReactionData.h(43): error C3861: 'log': identifier not found
```

These changes were introduced in #982. Unfortunately, I'm not that familiar with compiling on Windows to know how to fix this. One would assume that the logarithm function would be part of a standard library... I'm also not sure why this wasn't caught by the CI suite.

**Steps to reproduce**

1. Compile the current `main` branch (908a2cc) on Windows with MSVC 14.2. It's unclear whether this is related to the specific version of the compiler, or the standard include directories, or what.

**System information**

- Cantera version: `main`
- OS: Windows 10
- MSVC 14.2, VS 2019

### PR DESCRIPTION
**Pull request by speth**
`std::log` is declared in `<cmath>`, which we usually include via `ct_defs.h`.

Fixes #999.

**Changes proposed in this pull request**

- include `ct_defs.h` in `ReactionData.h`
- Run the 'docs' CI build without using the precompiled header (chosen because it's the fastest CI job, so will be least impacted by the time cost of not using the PCH)

**If applicable, fill in the issue number this pull request is fixing**

Fixes #

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
Congrats on #1000! Any idea why CI didn't catch this?

**Comment by ischoegl** [comment]
:tada: for 1000 also! I ran into the same thing in #995 yesterday, see dfadf6002cf5974f6eb229f853deb85de47d393f. Absolutely no idea why CI didn't catch it ... *Edit: updated my commit so it is consistent with this fix*

**Comment by speth** [comment]
Oh, I think I have a guess as why this wouldn't show up in the CI. Did your build have the use of the precompiled header disabled for some reason? Without the precompiled header, this should have been an error on every platform, but the PCH automatically gives you `<cmath>` among other things. Maybe it's worth having one of the CI builds run without that option turned on.

**Comment by speth** [comment]
I confirmed that building `main` with `use_pch=n` gives an error (Clang complains that `std` isn't defined, never mind `std::log`).

I modified the `docs` build to disable using the PCH. I don't want to do it on any of the other CI jobs because the PCH has a pretty significant effect on the build time.

**Comment by bryanwweber** [comment]
Confirmed this fixed the issue for me. Thanks for the quick fix @speth!
