### ISSUE TITLE
Compilation error with SUNDIALS 6.0 and 6.1

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1771]
Compilation of `CVodesIntegrator.cpp` currently fails with SUNDIALS 6.0 and 6.1. This occurs because the method `CVodeGetNumStepSolveFails` is only available in SUNDIALS 6.2 and newer. However, it is currently conditioned only on a check of `#if SUNDIALS_VERSION_MAJOR >= 6`:

https://github.com/Cantera/cantera/blob/5393a886a0fe56cdeaa6e3ca09b5ef921bd39a6d/src/numerics/CVodesIntegrator.cpp#L614-L618

This is a regression introduced in 9319ce98a78616a7f1f8a327d88457b174c70ee9, where the check was fixed to eliminate a typo (`CT_SUNDIALS_VERION`) that resulted in `CVodeGetNumStepSolveFails` never being called even for SUNDIALS 6.2 and newer.
