### PR TITLE
Preamble to InterfaceKinetics refactoring

### LINKED ISSUE #131: Optionally disable legacy reactions in Cantera 2.6
**Abstract**

At the moment, there already is a preprocessor flag `CT_NO_LEGACY_REACTIONS_26` introduced in `Reaction.h`, although it remains untested (at the moment, I am aware of at least one instance where toggling this flag will result in compilation errors). In order to ensure that the new framework introduced in #87 works without legacy support, the use of this preprocessor flag (or an additional `CT_NO_LEGACY_26`) could be extended to completely eliminate legacy reactions (as well as various CTI/XML tags). 

The flag could be adopted in `SCons`

**Motivation**

Describe the need for the work being done:

* What problem is it trying to solve? ... ensure that changes introduced in 2.6 are feature complete and do not rely on legacy objects.
* Who is affected by the change? ... early adopters and developers
* Why is this a good solution? ... the preprocessor will allow for CI tests without legacy support prior to the 2.6 release; deprecated code is automatically marked. As 2.6 is the last release to include legacy features, this will add a layer ensuring that everything is ready for the transition to 3.0.

**Alternatives**

Just make sure that toggling the flag to change defaults works (while still adding a CI runner that covers this configuration).

*Edit: Changes proposed in Cantera/cantera#1184 largely address this issue, as remaining 'hybrid' implementations no longer use legacy objects.*

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

This PR seeks to address several issues that came up while working on #1181.

- Fix compilation errors if `NO_LEGACY_REACTIONS_26` is set
- Streamline nomenclature for `activationEnergy` in the context of `BlowersMasel` ... use `effectiveActivationEnergy` for version that includes dependency on thermodynamic state (same will be introduced for `ReactionRate` classes that handle interface reactions).
- Limit use of `Arrhenius` ... clarify as `Arrhenius2` in legacy framework and make it equivalent with `ArrheniusBase` in new framework (`ArrheniusBase` should be renamed to `Arrhenius` after Cantera 2.6).  *Note: Defining a reduced `Arrhenius(Base)` class will also allow for additional templated classes - see e.g. Cantera/enhancements#133.*
- Remove leftover '3' from `ChebyshevRate(3)`
- Calculate `deltaH` within `BlowersMasel` without requiring associated `Kinetics` object

**If applicable, fill in the issue number this pull request is fixing**

* Preamble to #1181 
* Closes Cantera/enhancements#131

**If applicable, provide an example illustrating new features this pull request is introducing**

This PR will allow to disable legacy reactions (actually `typedef`s) from `SCons` as
```
$ scons build no_legacy_reactions=y
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
@speth ... this should take care of a lot of accumulated lint, and clearly mark legacy objects wherever used. Efficient handling of the `BlowersMasel` API will be important for #1181, where some preparatory work is done here. The new CI runner ensures that the `typedef Arrhenius2 Arrhenius` can be safely disabled.

There should be only minimal overlap with #1183 (if any). I added one instance of `setContext`, which I believe is a workable solution to the removal of remaining `Reaction` specializations that involve third bodies.

**Comment by ischoegl** [comment]
@speth ... rebased now that #1183 is merged. Once this PR is resolved, I can get back to InterfaceKinetics (#1181).

File: include/cantera/kinetics/RxnRates.h [hunk 1]
```diff
@@ -342,14 +220,17 @@ class PlogRate final : public ReactionRate
     PlogRate();
 
     //! Constructor from Arrhenius rate expressions at a set of pressures
-    explicit PlogRate(const std::multimap<double, Arrhenius>& rates);
+    explicit PlogRate(const std::multimap<double, ArrheniusBase>& rates);
+
+    //! Constructor using legacy Arrhenius2 framework
+    PlogRate(const std::multimap<double, Arrhenius2>& rates);
```
Comment (speth) [inline include/cantera/kinetics/RxnRates.h]: Single-argument constructor should usually be marked `explicit`.

File: include/cantera/kinetics/RxnRates.h [hunk 2]
```diff
@@ -469,18 +357,18 @@ class PlogRate final : public ReactionRate
      * @deprecated  Behavior to change after Cantera 2.6.
      *              @see getRates for new behavior.
      */
-    std::vector<std::pair<double, Arrhenius> > rates() const;
+    std::vector<std::pair<double, Arrhenius2> > rates() const;
```
Comment (speth) [inline include/cantera/kinetics/RxnRates.h]: One minor formatting thing that can be cleaned up here would be to drop the space between the two closing `>` (a wart that was fixed by C++11).

File: include/cantera/kinetics/Falloff.h [hunk 3]
```diff
@@ -104,8 +104,8 @@ class FalloffRate : public ReactionRate
         updateTemp(T, m_work.data());
         FalloffData data;
         data.update(T);
-        m_rc_low = m_lowRate.evalFromStruct(data);
-        m_rc_high = m_highRate.evalFromStruct(data);
+        m_rc_low = m_lowRate.evalRate(data.logT, data.recipT);
+        m_rc_high = m_highRate.evalRate(data.logT, data.recipT);
```
Comment (speth) [inline include/cantera/kinetics/Falloff.h]: At this point, we might as well just call `evalRate(std::log(T), 1/T)` and not bother with the `FalloffData` object for this function.

File: include/cantera/kinetics/FalloffMgr.h [hunk 4]
```diff
@@ -1,5 +1,8 @@
 /**
  *  @file FalloffMgr.h
+ *
+ *  @deprecated  Deprecated in Cantera 2.6 and removed thereafter. Replaced by
+ *      FalloffRate objects managed by MultiRate evaluators.
```
Comment (speth) [inline include/cantera/kinetics/FalloffMgr.h:5]: In addition to marking the header file as deprecated, I think it would be good to mark the `FalloffMgr` class deprecated as well.

File: include/cantera/kinetics/Arrhenius.h [hunk 5]
```diff
@@ -54,17 +64,25 @@ class ArrheniusBase : public ReactionRate
...
+    //! Check rate expression
+    void checkRate(const std::string& equation, const AnyMap& node);
 
-    //! Return parameters - required for legacy framework
-    //! @todo: merge with single-parameter version after removal of old framework
-    virtual void getParameters(AnyMap& node, const Units& rate_units) const;
+    //! Evaluate reaction rate
+    double evalRate(double logT, double recipT) const {
+        return m_A * std::exp(m_b * logT - m_Ea_R * recipT);
+    }
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h:83]: Having this as a non-virtual function in the base class used by `BlowersMaselRate` and `TwoTempPlasmaRate` seems like it will lead to some unfortunate surprising behavior. I'm starting to wonder if we're trying to hard to make those two classes fit into a heirarchy that doesn't quite fit.

File: include/cantera/kinetics/Arrhenius.h [hunk 6]
```diff
@@ -400,32 +439,31 @@ class BlowersMaselRate final : public ArrheniusBase
...
     //! Return the bond dissociation energy *w* [J/kmol]
     double bondEnergy() const {
-        return m_w_R * GasConstant;
+        return m_E4_R * GasConstant;
     }
 
 protected:
-    double m_w_R; //!< Bond dissociation energy (in temperature units)
+    //! Pairs of species indices and multiplers to calculate enthalpy change
+    std::vector<std::pair<size_t, double>> m_multipliers;
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h]: `m_stoich_coeffs` would be a more descriptive name of what these are rather than just how they're used.

File: include/cantera/kinetics/Arrhenius.h [hunk 7]
```diff
@@ -170,8 +189,14 @@ class ArrheniusRate final : public ArrheniusBase
 
     virtual void getParameters(AnyMap& node) const override;
 
+    void check(const std::string& equation, const AnyMap& node) {
+        checkRate(equation, node);
+    }
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h:200]: This needs to be marked `override`, and I suppose, `virtual` (likewise for the other classes derived from `ArrheniusBase`)

File: include/cantera/kinetics/RateCoeffMgr.h [hunk 8]
```diff
@@ -1,5 +1,8 @@
 /**
  *  @file RateCoeffMgr.h
+ *
+ *  @deprecated  Deprecated in Cantera 2.6 and removed thereafter. Replaced by
+ *      ReactionRate objects managed by MultiRate evaluators.
```
Comment (speth) [inline include/cantera/kinetics/RateCoeffMgr.h:5]: Likewise here, I think the `Rate1` class itself should be marked as deprecated.

File: include/cantera/kinetics/ReactionData.h [hunk 9]
```diff
@@ -45,13 +45,15 @@ struct ReactionData
...
     virtual void update(double T, double extra);
 
-    //! Update data container based on *bulk* phase state
+    //! Update data container based on thermodynamic phase state
     /**
      * This update mechanism is used by Kinetics reaction rate evaluators.
      * @returns  A boolean element indicating whether the `evalFromStruct` method
      *      needs to be called (assuming previously-calculated values were cached)
+     *
+     * @todo  Remove Kinetics argument
```
Comment (speth) [inline include/cantera/kinetics/ReactionData.h:54]: How do you anticipate removing the `Kinetics` argument? I had been expecting that since the `Kinetics` object actually knows about all of the phases participating in a reaction, that was the only way to guarantee that you had everything you needed available.

File: src/kinetics/BulkKinetics.cpp [hunk 10]
```diff
@@ -143,6 +143,7 @@ bool BulkKinetics::addReaction(shared_ptr<Reaction> r, bool resize)
 
         // Set index of rate to number of reaction within kinetics
         rate->setRateIndex(nReactions() - 1);
+        rate->setContext(*r.get(), *this);
```
Comment (speth) [inline src/kinetics/BulkKinetics.cpp]: You can write `*r.get()` as just `*r`. Likewise below in `modifyReaction`.

File: src/kinetics/FalloffFactory.cpp [hunk 11]
```diff
@@ -1,5 +1,8 @@
 /**
  *  @file FalloffFactory.cpp
+ *
+ *  @deprecated  Deprecated in Cantera 2.6 and removed thereafter. Replaced by
+ *      FalloffRate objects managed by MultiRate evaluators.
```
Comment (speth) [inline src/kinetics/FalloffFactory.cpp:5]: No point removing this, but I would say that for future reference there's never really a need to mark a `.cpp` file as deprecated, since there's way to reference it externally anyway.

File: src/kinetics/RxnRates.cpp [hunk 12]
```diff
@@ -32,56 +30,37 @@ Arrhenius2::Arrhenius2(const AnyValue& rate,
...
-
-void BlowersMasel2::getParameters(AnyMap& rateNode, const Units& rate_units) const
+void Arrhenius2::getParameters(AnyMap& node, const Units& rate_units) const
 {
     if (rate_units.factor() != 0.0) {
-        rateNode["A"].setQuantity(preExponentialFactor(), rate_units);
+        node["A"].setQuantity(m_A, rate_units);
     } else {
-        rateNode["A"] = preExponentialFactor();
+        node["A"] = m_A;
```
Comment (speth) [inline src/kinetics/RxnRates.cpp]: I know this isn't followed universally, but one of the ways to make sure that objects have a complete interface without having to interact with a specific input format is by using public methods in the `getParameters`/`setParameters`-like methods instead of just accessing all the member variables directly. I don't think we necessarily need to enforce this rigidly, but I think it's worth at least leaving cases that use that style as-is.

File: src/kinetics/RxnRates.cpp [hunk 13]
```diff
@@ -240,17 +228,19 @@ void PlogRate::validate(const std::string& equation)
     }
 }
 
-std::vector<std::pair<double, Arrhenius> > PlogRate::rates() const
+std::vector<std::pair<double, Arrhenius2> > PlogRate::rates() const
 {
-    warn_deprecated("PlogRate::rates", "Behavior to change after Cantera 2.6; "
-        "see getRates() for new behavior.");
     auto rateMap = getRates();
```
Comment (speth) [inline src/kinetics/RxnRates.cpp:233]: Why did the deprecation warning here go away?

File: interfaces/cython/cantera/reaction.pyx [hunk 14]
```diff
@@ -120,72 +120,102 @@ cdef class ReactionRate:
...
-            self.set_cxx_object()
+    Base class collecting commonly used features of Arrhenius-type rate objects.
+    """
+    _reaction_rate_type = None
 
-    cdef CxxArrheniusRate* cxx_object(self):
-        return <CxxArrheniusRate*>self.rate
+    def _cinit(self, input_data, **kwargs):
+        """Helper function called by __cinit__"""
+        if self._reaction_rate_type is None:
```
Comment (speth) [inline interfaces/cython/cantera/reaction.pyx:137]: I think it would help to explain why this can't just be the implementation of `__cinit__` directly. If I'm understanding it correctly, this comes down to the arguments for the derived classes being slightly different, but not wanting to make these all be keyword-only?

File: interfaces/cython/cantera/reaction.pyx [hunk 15]
```diff
@@ -120,72 +120,102 @@ cdef class ReactionRate:
...
+            self._from_dict(input_data)
+        elif all([kwargs[k] is not None for k in kwargs]):
+            self._from_parameters(*[kwargs[k] for k in kwargs])
+        elif all([kwargs[k] is None for k in kwargs]) and input_data is None:
+            self._from_dict({})
+        elif input_data:
+            raise TypeError("Invalid parameter 'input_data'")
+        else:
+            par_list = [f"'{k}'" for k in kwargs]
+            par_string = ", ".join([par_list[:-1]])
```
Comment (speth) [inline interfaces/cython/cantera/reaction.pyx]: I think this needs to be:
```suggestion
            par_string = ", ".join(par_list[:-1])
```

File: interfaces/cython/cantera/reaction.pyx [hunk 16]
```diff
@@ -120,72 +120,102 @@ cdef class ReactionRate:
...
-    A reaction rate coefficient which depends on temperature only and follows
-    the modified Arrhenius form:
-
-    .. math::
-
-        k_f = A T^b \exp{-\tfrac{E}{RT}}
-
-    where ``A`` is the `pre_exponential_factor`, ``b`` is the `temperature_exponent`,
-    and ``Ea`` is the `activation_energy`.
+cdef class _ArrheniusTypeRate(ReactionRate):
```
Comment (speth) [inline interfaces/cython/cantera/reaction.pyx]: This class needs to be added to `kinetics.rst`

File: test/kinetics/kineticsFromScratch3.cpp [hunk 17]
```diff
@@ -136,11 +136,11 @@ TEST_F(KineticsFromScratch3, add_plog_reaction)
     //                [(100.0, 'atm'), 5.963200e+56, -11.529, 52599.6])
     Composition reac = parseCompString("H2:1, O2:1");
     Composition prod = parseCompString("OH:2");
-    std::multimap<double, Arrhenius> rates {
-        { 0.01*101325, Arrhenius(1.212400e+16, -0.5779, 10872.7 / GasConst_cal_mol_K) },
-        { 1.0*101325, Arrhenius(4.910800e+31, -4.8507, 24772.8 / GasConst_cal_mol_K) },
-        { 10.0*101325, Arrhenius(1.286600e+47, -9.0246, 39796.5 / GasConst_cal_mol_K) },
-        { 100.0*101325, Arrhenius(5.963200e+56, -11.529, 52599.6 / GasConst_cal_mol_K) }
+    std::multimap<double, ArrheniusBase> rates {
+        { 0.01*101325, ArrheniusBase(1.212400e+16, -0.5779, 10872.7 * 4184.0) },
```
Comment (speth) [inline test/kinetics/kineticsFromScratch3.cpp:140]: You're anticipating that `ArrheniusBase` will become just `Arrhenius` eventually, right? I really hope this change from temperature units to energy units won't catch too many people by surprise.

File: include/cantera/kinetics/Arrhenius.h [hunk 18]
```diff
@@ -77,10 +95,11 @@ class ArrheniusBase : public ReactionRate
...
     }
 
-    //! Return the intrinsic activation energy *Ea* [J/kmol]
+    //! Return the activation energy *Ea* [J/kmol]
     //! The value corresponds to the constant specified by input parameters;
-    //! in the simplest case, this is equal to the activation energy itself
-    double intrinsicActivationEnergy() const {
+    //! class specializations may provide alternate definitions that describe
+    //! an effective activation energy that depends on the thermodynamic state.
+    double activationEnergy() const {
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h:108]: Big :+1: on this change in terminology -- I think it's much better.

**Review by speth — CHANGES_REQUESTED** [review]
Thanks for splitting this out, since a lot of this is just reorganization and name changes. I think it will make reviewing #1181 a fair bit easier.

I like the addition of `setContext` -- it makes a lot of sense to have a function that can be called to set things like species indices that can be resolved at the point when a reaction is added to a Kinetics object, but not before.

File: include/cantera/kinetics/ReactionData.h (hunk 9 above)
Comment (ischoegl) [reply include/cantera/kinetics/ReactionData.h:54]: Whatever is needed can already be set/buffered by `setContext`. Once `InterfaceKinetics` is complete, I believe that the `Kinetics` argument can be safely removed.

File: src/kinetics/RxnRates.cpp (hunk 13 above)
Comment (ischoegl) [reply src/kinetics/RxnRates.cpp:233]: In order to properly split `Arrhenius` into legacy and new behavior, this route is used again whenever you instantiate from XML and/or access the legacy objects. I'm not sure that this is the best place to make noisy warnings.

In a nutshell, this object needs to be instantiated both from `PlogRate` as well as `PlogReaction2`, which use `ArrheniusBase/Arrhenius3` and `Arrhenius2`, respectively.

File: interfaces/cython/cantera/reaction.pyx (hunk 14 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reaction.pyx:137]: Correct. As far as I'm aware, Cython doesn't allow for `__cinit__` overloads.

File: interfaces/cython/cantera/reaction.pyx (hunk 16 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reaction.pyx]: Ok. While this is a hidden class, the documentation needs to be added, correct? Is there a way to specify inherited members (by level) in Sphinx?

File: test/kinetics/kineticsFromScratch3.cpp (hunk 17 above)
Comment (ischoegl) [reply test/kinetics/kineticsFromScratch3.cpp:140]: ~This is correct (to clarify, I just renamed `ArrheniusBase` to `Arrhenius3`).~ *Edit: there's one option I want to test next where wouldn't be the case* ... I'm not sure that many people instantiate `Arrhenius` directly, and it would be odd to have a default unit that is different from the YAML specification.

One way would be to add an optional boolean. At the same time, it is really `ArrheniusRate` that is a successor to `Arrhenius2`; as this goes hand-in-hand with the introduction of YAML, I believe it is the right time to switch.

As an aside, the Python API already used energy units by default; as this is (presumably) the most commonly used API, I do not anticipate many problems.

File: include/cantera/kinetics/Arrhenius.h (hunk 5 above)
Comment (ischoegl) [reply include/cantera/kinetics/Arrhenius.h:83]: I added an `@internal` and augmented the docstring mentioning that this method is not meant for overloading.

Overall, the `Arrhenius` class is purely non-virtual, as none of the methods are meant to be overloaded.

File: interfaces/cython/cantera/reaction.pyx (hunk 16 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reaction.pyx]: I ended up un-hiding the class in Python, and added it to `kinetics.rst` as requested.

**Comment by ischoegl** [comment]
@speth ... thank you for your review! Beyond addressing review comments, I also renamed `ArrheniusBase` to `Arrhenius3` to clarify the anticipated renaming. I believe all concerns are addressed ...

*PS: removed a superfluous `ReactionRate::activationEnergy()` after requesting the review - had overlooked that.*

**Comment by ischoegl** [comment]
@speth ... I addressed all comments. GH actions appears down for the time being; I'll try to re-trigger later on. Regarding the renaming of `ArrheniusBase`, I am tabling this as there is another tweak that I'd like to test first.

**Comment by ischoegl** [comment]
GH actions are back up, and everything ran through …

File: include/cantera/kinetics/ReactionData.h (hunk 9 above)
Comment (speth) [reply include/cantera/kinetics/ReactionData.h:54]: You want to make the `Reaction` hold a pointer back to the `Kinetics` object if it needs that data, then?

File: src/kinetics/RxnRates.cpp (hunk 13 above)
Comment (speth) [reply src/kinetics/RxnRates.cpp:233]: I wonder if we need to have a way to do noisy warnings that are silenced if you're using CTI/XML input. Right now, we have a lot of functions and classes that are marked as deprecated but don't emit warnings for this reason.

File: test/kinetics/kineticsFromScratch3.cpp (hunk 17 above)
Comment (speth) [reply test/kinetics/kineticsFromScratch3.cpp:140]: You're right that this is probably not the most common means of instantiating `Arrhenius` objects for end-users. One thing that would be simple to do, though not foolproof, would be to call out this difference in the Doxygen deprecation note that describes `ArrheniusBase` as the replacement. Though right now `Arrhenius2` is still missing such a marking.

Comment (ischoegl) [reply test/kinetics/kineticsFromScratch3.cpp:140]: I think that is appropriate. Once `InterfaceKinetics` is done, there won't be a problem raising noisy warnings, etc..

Comment (ischoegl) [reply test/kinetics/kineticsFromScratch3.cpp:140]: I believe that adding a `todo` in the docstring of the constructor is likely the best option for the moment (which I just added).

File: interfaces/cython/cantera/reaction.pyx (hunk 14 above)
Comment (speth) [reply interfaces/cython/cantera/reaction.pyx:137]: `__cinit__` can be defined in both the base and derived classes, and functions more like a C++ constructor than the `__init__` method, in that it is always called for all classes in the hierarchy, starting with the base class. The one thing which I guess is relevant here is that default arguments defined in the child class's `__cinit__` won't be seen by the parent class's `__cinit__`.

In any case, the behavior in question is "overriding", not "overloading" which Python doesn't do at all.

File: include/cantera/kinetics/Arrhenius.h [hunk 19]
```diff
@@ -370,14 +390,34 @@ class BlowersMaselRate final : public ArrheniusBase
 
     virtual void getParameters(AnyMap& node) const;
 
-    double evalFromStruct(const BlowersMaselData& shared_data) {
-        double deltaH_R;
+    void check(const std::string& equation, const AnyMap& node) override {
+        checkRate(equation, node);
+    }
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h:396]: Sorry I missed this before, but there are several other functions in `BlowersMaselRate` that now need to be marked `override` (at least, to avoid getting warnings from Clang). Namely, `newMultiRate`, `type`, `setParameters`, and `getParameters`.

Comment (ischoegl) [reply include/cantera/kinetics/Arrhenius.h:396]: No problem - fixed. Should probably switch to clang!

File: src/kinetics/RxnRates.cpp (hunk 13 above)
Comment (ischoegl) [reply src/kinetics/RxnRates.cpp:233]: Maybe ... at the same time, it may be a good incentive to switch to YAML. I'd advocate for issuing warnings once `InterfaceKinetics` is done, and `Arrhenius2` is only used for XML/CTI.

File: include/cantera/kinetics/ReactionData.h (hunk 9 above)
Comment (ischoegl) [reply include/cantera/kinetics/ReactionData.h:54]: I think it's not strictly necessary, but we can discuss when the time comes.

File: interfaces/cython/cantera/reaction.pyx (hunk 14 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reaction.pyx:137]: > [...] functions more like a C++ constructor than the `__init__` method, in that it is always called for all classes in the hierarchy, starting with the base class The one thing which I guess is relevant here is that default arguments defined in the child class's `__cinit__` won't be seen by the parent class's `__cinit__`.

Thanks - yes, the call-order is relevant here, which is why the regular `__cinit__` route doesn't work.

**Review by speth — APPROVED** [review]
Thanks for the updates, @ischoegl. This looks good to me.
